version: "3.7"
services:
  # The Application
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
    tty: true
    networks: 
      - streaming_network
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.Dockerfile
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    tty: true
    networks: 
      - streaming_network
    depends_on:
      - app
  # The Database
  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - ./docker/mariadb/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      # - ./docker/mariadb/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "33061:3306"
    tty: true
    networks: 
      - streaming_network
    depends_on:
      - app

networks:
  streaming_network:
    driver: bridge